#pragma once

EXTERN_C const GUID CLSID_CamIP;
EXTERN_C const GUID CLSID_CamIP0;
EXTERN_C const GUID CLSID_CamIP1;
EXTERN_C const GUID CLSID_CamIP2;
EXTERN_C const GUID CLSID_CamIP3;
EXTERN_C const GUID CLSID_CamIP4;
EXTERN_C const GUID CLSID_CamIP5;
EXTERN_C const GUID CLSID_CamIP6;
EXTERN_C const GUID CLSID_CamIP7;
EXTERN_C const GUID CLSID_CamIP8;
EXTERN_C const GUID CLSID_CamIP9;
